# Generated by Django 2.2.13 on 2020-10-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='bond',
            name='legal_name',
            field=models.CharField(max_length=50),
        ),
    ]
