# Generated by Django 2.2.13 on 2020-10-15 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0002_auto_20201013_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='nomatch', message='Incorrect format: should be 12 alphanumeric characters', regex='^[0-9a-zA-Z]{12}$')]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Incorrect format: should be 20 alphanumeric characters', regex='^[0-9a-zA-Z]{20}$')]),
        ),
    ]
